version: "3.1"

services:
  mongo:
    image: mongo
    volumes:
      - skap_dbdata:/data/db
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/
      ME_CONFIG_BASICAUTH: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_DASH_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_DASH_PASS}

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: always
    environment:
      NODE_ENV: development
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  skap_dbdata:
  node_modules:
