version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: always
    environment:
      NODE_ENV: development
      VITE_WEBSOCKET_URL: ws://localhost:8080/cable
      VITE_BROADCAST_URL: http://localhost:8090/_broadcast
      VITE_API_BASE_URL: http://localhost:3000
    command: npm run dev
    env_file:
      - .env

volumes:
  node_modules:
