version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: always
    environment:
      NODE_ENV: development
    command: npm run dev
    env_file:
      - .env

volumes:
  node_modules: {}
