version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    restart: always
    environment:
      - NODE_ENV=production
    command:
      - node
      - '--use-openssl-ca'
      - app.js
    env_file:
      - .env
    volumes:
      - node_modules:/app/node_modules

  nginx:
    image: nginx:latest
    ports:
      - '443:443'
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/skap.mcgi.services/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/skap.mcgi.services/privkey.pem:/etc/nginx/certs/privkey.pem
    depends_on:
      - app

volumes:
  node_modules: {}
